### ISSUE TITLE
Release car_demo

### ISSUE THREAD

**Issue by sloretz** [osrf/car_demo#3]
@tfoote, thoughts? The first 4 are copied from Brian's email.

- [x] make the repo public
- [x] tutorial explaining how to get, build, and run the code (#5)
- [x] push a docker image to dockerhub
- [x] screenshots to combine with the video for a blog post
- [x] add all dependencies to package.xml's (#12)
- [x] Move main launch file (gazebo.launch) out of prius_description and rename (#10)
- [x] ~~Bloom release to kinetic/lunar? Not really needed for blog post purposes~~
- [x] Remove duplicate prius_hybrid model from prius_plugin
- [x] ~~CmakeLists.txt install rules for launch files/models #9~~
- [x] Remove Hybrid.obj, since it was split into 3 smaller meshes
- [x] Fix steering wheel being too high/wrong angle (#8)
- [x] FIx model loading. We're downloading all gazebo models from the database. But I noticed that the ones we need look to be already in the repo. Or else remove the ones from the repo. (#7)
- [x] CHeck licenses on all files.

**Comment by tfoote** [comment]
repo public, and image pushed to dockerhub

**Comment by sloretz** [comment]
https://www.osrfoundation.org/simulated-car-demo/

Released! Closing.
